# Generated by Django 3.0 on 2022-04-19 08:03

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='media_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pics')),
                ('image_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
