# Generated by Django 3.2.4 on 2022-02-01 04:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('histroy_title', models.CharField(max_length=200)),
                ('histroy_content', ckeditor.fields.RichTextField()),
                ('histroy_img', models.ImageField(blank=True, upload_to='pics')),
                ('secound01_histroy_content', ckeditor.fields.RichTextField()),
                ('secound_histroy_img', models.ImageField(blank=True, upload_to='pics')),
                ('secound02_histroy_content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ministry_Histroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_establish', models.CharField(max_length=100)),
                ('year_establish_title', models.CharField(max_length=100)),
                ('establish_description_title', models.CharField(max_length=200)),
                ('establish_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ministry_Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_in', models.CharField(max_length=100)),
                ('year_establish_name', models.CharField(max_length=100)),
                ('establish_description_img', models.ImageField(blank=True, upload_to='pics')),
                ('establish_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaries_Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year_in', models.CharField(max_length=100)),
                ('year_establish_name', models.CharField(max_length=100)),
                ('establish_description_img', models.ImageField(blank=True, upload_to='pics')),
                ('establish_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
