# Generated by Django 3.2.4 on 2022-02-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('si_no', models.IntegerField()),
                ('Name_of_International_and_Regional_org', models.CharField(max_length=200)),
                ('Membership_Joining_Date', models.IntegerField()),
            ],
        ),
    ]
