# Generated by Django 3.2.4 on 2022-02-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_about_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='about_us',
            new_name='about_u',
        ),
    ]
