# Generated by Django 3.0 on 2022-04-20 08:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_img', models.ImageField(blank=True, upload_to='pics')),
                ('event_img2', models.ImageField(blank=True, upload_to='pics')),
                ('event_img3', models.ImageField(blank=True, upload_to='pics')),
                ('event_img4', models.ImageField(blank=True, upload_to='pics')),
                ('event_img5', models.ImageField(blank=True, upload_to='pics')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('event_description', ckeditor.fields.RichTextField()),
                ('event_file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='image_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='information_and_download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('download_link', models.CharField(blank=True, max_length=300)),
                ('info_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('post_img', models.ImageField(blank=True, upload_to='pics')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], max_length=100)),
                ('section', models.CharField(choices=[('landimg', 'landimg'), ('Popular', 'Popular'), ('Recent', 'Recent'), ('latest', 'latest')], max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_title', models.CharField(max_length=100)),
                ('press_img', models.ImageField(blank=True, upload_to='pics')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('press_description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, upload_to='pics')),
                ('profile_designation', models.CharField(max_length=200)),
                ('profile_name', models.CharField(max_length=200)),
                ('profile_bio', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.IntegerField(blank=True)),
                ('tender_title', models.CharField(max_length=100)),
                ('tender_img', models.ImageField(blank=True, upload_to='pics')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('tender_description', ckeditor.fields.RichTextField()),
                ('tender_file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='vacancie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=100)),
                ('vacancy_img', models.ImageField(blank=True, upload_to='pics')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('vacancy_description', ckeditor.fields.RichTextField()),
                ('vacancy_file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.post')),
            ],
        ),
    ]
