# Generated by Django 3.2.4 on 2022-02-01 02:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_vacancie_vacancy_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('event_img', models.ImageField(blank=True, upload_to='pics')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('event_description', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
