# Generated by Django 3.0 on 2022-04-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_auto_20220420_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
