# Generated by Django 3.2.4 on 2022-02-01 08:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_pressrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='information_and_download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('download_link', models.CharField(blank=True, max_length=300)),
                ('info_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
