# Generated by Django 3.0 on 2022-04-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_auto_20220422_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank='True', choices=[('announcement', 'Announcement'), ('event', 'Event'), ('information', 'Information'), ('notifications', 'Notifications')], max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
