# Generated by Django 3.0 on 2022-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='tender_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
