# Generated by Django 3.0 on 2022-04-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_merge_20220413_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='vacancie',
            name='vacancy_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
