# Generated by Django 3.0 on 2022-05-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0007_auto_20220506_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='tender_img',
        ),
        migrations.RemoveField(
            model_name='vacancie',
            name='vacancy_img',
        ),
    ]
