# Generated by Django 3.0 on 2022-05-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0008_auto_20220512_1003'),
        ('indexapp', '0002_auto_20220515_0449'),
    ]

    operations = [
    ]
