# Generated by Django 3.0 on 2022-05-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0009_merge_20220515_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank='True', choices=[('Announcement', 'Announcements'), ('Event', 'Events'), ('Information', 'Informations'), ('Notification', 'Notifications')], max_length=100, null='True'),
        ),
    ]
