# Generated by Django 3.0 on 2022-04-13 17:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0009_image_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.IntegerField(blank=True)),
                ('tender_title', models.CharField(max_length=100)),
                ('tender_img', models.ImageField(blank=True, upload_to='pics')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('tender_description', ckeditor.fields.RichTextField()),
                ('tender_file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
    ]
