# Generated by Django 3.0 on 2022-04-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0010_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='media_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='pics')),
                ('image_description', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='image_slider',
        ),
    ]
