# Generated by Django 3.0 on 2022-04-19 07:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_auto_20220419_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_gallery',
            name='image_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
