# Generated by Django 3.0 on 2022-04-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0012_auto_20220419_0727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
