# Generated by Django 3.0 on 2022-04-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0013_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img2',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_img3',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
