# Generated by Django 3.0 on 2022-04-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0014_auto_20220419_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_img4',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_img5',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
