# Generated by Django 3.0 on 2022-04-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0016_auto_20220420_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesIpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='indexapp.LikesIpModel'),
        ),
    ]
