# Generated by Django 3.0 on 2022-04-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0017_auto_20220420_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='likes',
        ),
        migrations.DeleteModel(
            name='LikesIpModel',
        ),
    ]
