# Generated by Django 3.0 on 2022-04-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220407_2108'),
        ('contact', '0002_auto_20220407_1311'),
    ]

    operations = [
    ]
