# Generated by Django 3.0 on 2022-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_merge_20220413_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=150)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
