# Generated by Django 3.0 on 2022-04-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
