# Generated by Django 3.0 on 2022-04-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactform_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='content',
        ),
    ]
