# Generated by Django 3.2.4 on 2022-02-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='annual_performance_agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400)),
                ('address_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
