# Generated by Django 3.0 on 2022-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0004_merge_20220413_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual_performance_agreement',
            name='address_link',
        ),
        migrations.AddField(
            model_name='annual_performance_agreement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
