# Generated by Django 3.0 on 2022-05-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0005_auto_20220520_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_performance_agreement',
            name='year',
            field=models.CharField(blank='True', choices=[('2016-2017', '2016-2017'), ('2017-2018', '2017-2018'), ('2018-2019', '2018-2019'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023'), ('2023-2024', '2023-2024')], max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
