# Generated by Django 3.0 on 2022-05-19 18:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0006_annual_performance_agreement_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='annual_performance_agreement',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
