# Generated by Django 3.0 on 2022-05-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0007_annual_performance_agreement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annual_performance_agreement',
            name='description',
        ),
    ]
