# Generated by Django 3.2.4 on 2022-02-01 05:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=200)),
                ('organogram_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
