# Generated by Django 3.2.4 on 2022-02-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0002_rename_organogram_top_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_Human_Resource', models.IntegerField()),
                ('name_of_Human_Resource', models.CharField(max_length=200)),
            ],
        ),
    ]
