# Generated by Django 3.2.4 on 2022-02-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0003_human_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='information_download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('download_link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='organogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('organogram_img', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
