# Generated by Django 3.2.4 on 2022-02-01 05:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='office_of_minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('mail_id', models.EmailField(blank=True, max_length=254)),
                ('phone_no', models.IntegerField(blank=True)),
                ('profile_img', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='office_of_secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('mail_id', models.EmailField(blank=True, max_length=254)),
                ('phone_no', models.IntegerField(blank=True)),
                ('profile_img', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='shortlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortlink_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='top_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=300)),
            ],
        ),
    ]
