# Generated by Django 3.0 on 2022-04-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0002_auto_20220407_2108'),
        ('whoiswho', '0003_auto_20220407_1401'),
    ]

    operations = [
    ]
