# Generated by Django 3.0 on 2022-05-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0005_auto_20220413_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ict_division',
            name='focal_person_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
