# Generated by Django 3.0 on 2022-05-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoiswho', '0006_ict_division_focal_person_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='focal_person_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='finance_division',
            name='focal_person_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='human_resource_division',
            name='focal_person_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internal_audit',
            name='focal_person_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='policy_planning_division',
            name='focal_person_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='procurement_section',
            name='focal_person_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
