# Generated by Django 3.2.4 on 2022-02-01 08:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='arts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rules_and_regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('info_icon', models.ImageField(blank=True, upload_to='pics')),
                ('info_count', models.IntegerField(blank=True)),
                ('info_title', models.CharField(blank=True, max_length=200)),
                ('info_info', models.CharField(blank=True, max_length=200)),
                ('slider_img', models.ImageField(blank=True, upload_to='pics')),
                ('slider_title', models.CharField(blank=True, max_length=200)),
                ('slider_name', models.CharField(blank=True, max_length=200)),
                ('report_report', models.CharField(blank=True, max_length=200)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
