# Generated by Django 3.0 on 2022-04-07 15:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_arts_guideline_report_rules_and_regulation_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='rules_and_regulation',
        ),
        migrations.AlterField(
            model_name='arts',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='info_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
