# Generated by Django 3.0 on 2022-04-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0003_auto_20220407_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regulation',
            new_name='regulations',
        ),
        migrations.RenameModel(
            old_name='rule',
            new_name='rules',
        ),
    ]
