# Generated by Django 3.0 on 2022-04-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0004_auto_20220407_2110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rules',
            new_name='rules_and_regulation',
        ),
        migrations.DeleteModel(
            name='regulations',
        ),
    ]
