# Generated by Django 3.0 on 2022-04-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_auto_20220407_2117'),
        ('publication', '0003_auto_20220407_1311'),
    ]

    operations = [
    ]
