# Generated by Django 3.0 on 2022-04-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_merge_20220413_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='act_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='guideline_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='rules_and_regulation',
            name='rule_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='statistic_file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
