# Generated by Django 3.0 on 2022-04-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_auto_20220420_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arts',
            name='act_file',
        ),
        migrations.RemoveField(
            model_name='guideline',
            name='guideline_file',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_file',
        ),
        migrations.RemoveField(
            model_name='rules_and_regulation',
            name='rule_file',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='statistic_file',
        ),
    ]
