# Generated by Django 3.0 on 2022-04-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0009_policy_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='guideline',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='rules_and_regulation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AddField(
            model_name='statistic',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
