# Generated by Django 3.0 on 2022-04-26 09:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0010_auto_20220426_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('SI_No', models.IntegerField(blank=True)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('copy_link', models.CharField(blank=True, max_length=400)),
                ('facebook', models.CharField(blank=True, max_length=400)),
                ('whatsapp', models.CharField(blank=True, max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('telegram', models.CharField(blank=True, max_length=400)),
                ('link_title', models.CharField(blank=True, max_length=100)),
                ('link_name', models.CharField(blank=True, max_length=100)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.RenameModel(
            old_name='rules_and_regulation',
            new_name='regulations',
        ),
    ]
