# Generated by Django 3.0 on 2022-05-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0013_hr_decisions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hr_decisions',
            new_name='hrdecisions',
        ),
    ]
