# Generated by Django 3.0 on 2022-05-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_auto_20220504_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hrdecisions',
        ),
    ]
