# Generated by Django 3.0 on 2022-05-23 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0015_delete_hrdecisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='content',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='copy_link',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='email',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='info_count',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='info_icon',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='info_info',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='info_title',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='link_name',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='link_title',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='report_report',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='slider_img',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='slider_name',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='slider_title',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='top_title',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='whatsapp',
        ),
    ]
