# Generated by Django 3.0 on 2022-04-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_img', models.ImageField(blank=True, upload_to='pics')),
                ('gallery_description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='media_gallery',
        ),
    ]
