# Generated by Django 3.0 on 2022-05-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220420_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagegallery',
            old_name='gallery_description',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='imagegallery',
            old_name='gallery_img',
            new_name='image',
        ),
    ]
