# Generated by Django 3.2.4 on 2022-02-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='top_title',
            old_name='top_title',
            new_name='top_title01',
        ),
    ]
