# Generated by Django 3.2.4 on 2022-02-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_rename_top_title_top_title_top_title01'),
    ]

    operations = [
        migrations.DeleteModel(
            name='top_title',
        ),
    ]
