# Generated by Django 3.2.4 on 2022-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0003_delete_top_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title01', models.CharField(max_length=200)),
            ],
        ),
    ]
