# Generated by Django 3.2.4 on 2022-02-01 05:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_top_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ongoing_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(max_length=200)),
                ('project_top_description', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SI_No', models.IntegerField()),
                ('Project_Title', models.CharField(max_length=200)),
                ('Project_Objective', models.CharField(max_length=300)),
                ('Project_Duration', models.IntegerField()),
                ('Progress', models.IntegerField()),
            ],
        ),
    ]
