# Generated by Django 3.2.4 on 2022-02-01 05:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0005_ongoing_project_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_Objective',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
