# Generated by Django 3.2.4 on 2022-02-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0006_alter_project_project_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_u',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url_address', models.CharField(max_length=300)),
            ],
        ),
    ]
