# Generated by Django 3.2.4 on 2022-02-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0007_about_u'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about_u',
        ),
    ]
