# Generated by Django 3.2.4 on 2022-02-01 06:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department_of_air_transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('phone_no', models.IntegerField(blank=True)),
                ('histroy_content', ckeditor.fields.RichTextField()),
                ('profile_img', models.ImageField(blank=True, upload_to='pics')),
                ('vision_title', models.CharField(blank=True, max_length=200)),
                ('vision_description', ckeditor.fields.RichTextField(blank=True)),
                ('mission_title', models.CharField(blank=True, max_length=200)),
                ('mission_description', ckeditor.fields.RichTextField(blank=True)),
                ('objective_title', models.CharField(blank=True, max_length=200)),
                ('objective_description', ckeditor.fields.RichTextField(blank=True)),
                ('number_of_Human_Resource', models.IntegerField(blank=True)),
                ('name_of_Human_Resource', models.CharField(blank=True, max_length=200)),
                ('website_link', models.CharField(blank=True, max_length=200)),
                ('facebook_link', models.CharField(blank=True, max_length=200)),
                ('address_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
